version: '3.8'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'Admin'
    ports:
      - "3307:3306"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql

