spring:
  datasource:
    url: jdbc:mysql://db:3306/localspringbootdb?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update